### ISSUE TITLE
Authentication error with RSiteCatalyst when using Knit, R Studio

### ISSUE THREAD

**Issue by jbarratt77** [gilliganondata/aa-ga-compare#7]
Hi Tim,
I'm trying to run this comparison using RStudio to produce a HTML output but receiving an error when I try to Knit to HTML.

`Line 10:  Error: Authentication options didn't match existing session token and not interactive session so unable to manually reauthenticate Execution halted `

Line 10 is:
`library(RSiteCatalyst)       # Package for getting the Adobe Analytics data`

It seems to work fine when I just 'Run All Chunks' but not when I use Knit.

Any ideas?

Josh

**Comment by jbarratt77** [comment]
I fixed it by changing `ga_auth()` to `ga_auth(".httr-oauth")`

These links were useful:
https://github.com/MarkEdmondson1234/googleAnalyticsR/issues/137
https://github.com/MarkEdmondson1234/googleAnalyticsR/issues/126
https://github.com/MarkEdmondson1234/googleAnalyticsR/issues/169

**Comment by gilliganondata** [comment]
Thanks for finding/posting the fix. OAuth gets really finicky in general, and especially so with RMarkdown. So, you're now explicitly looking for a saved token in a token file named `.httr-oauth` (which is the default name). That should, indeed, work. If that token winds up expiring, you'll need to re-auth (outside of knitting) to refresh the file. But, that shouldn't be a big deal -- might not be something you run into.
